### ISSUE TITLE
Double floating toolboxes on 2014-09-26b.

### ISSUE THREAD

**Issue by dpcox** [notconscious/dokuwiki-template-adoradark#5]
When I use it I have two floating toolboxes on the right of the screen as can be seen in the attached screen shot.  I'm running release 2014-09-29b of Dokuwiki.

![template-problem](https://cloud.githubusercontent.com/assets/10778665/5983139/977f0dc8-a898-11e4-979b-a84c782e17e7.jpg)

**Comment by mtik00** [comment]
Same here.  I can't quite figure out where it's coming from, as that part of ``main.php`` doesn't different from the base dokuwiki template.  Of course, I also don't know what I'm doing when it comes to PHP/CSS.

**Comment by ruzaq** [comment]
I've just semi-fixed this problem by changing display value from "inline-block" to "none" in adoradark/css/pagetools.less

#dokuwiki__pagetools ul li a:before {
    content: url(images/pagetools-sprite.png?v=2);
    display: none;
    font-size: 0;
    line-height: 0;
}

**Comment by notconscious** [comment]
I wasn't able to reproduce this on the latest release of Dokuwiki (Elenor of Tsort) so I'm closing this issue. If it happens again, please open another issue!
